### ISSUE TITLE
Support Exceptionless 2.0 logs

### ISSUE THREAD

**Issue by niemyjski** [enkafan/Serilog.Sinks.ExceptionLess#3]
We are announcing a preview very soon for Exceptionless 2.0 which supports logs. I was wondering if you could update the package to support 2.0. I'd be more than happy to meet with you and pair / help maintain this project. Here is a link to the preview: https://be.exceptionless.io/

Here is our nlog target for an idea :).

https://github.com/exceptionless/Exceptionless/tree/master/Source/Clients/NLog

**Comment by niemyjski** [comment]
It's worth noting that 2.0 now has a portable class library. I'm not sure if serilog has a portable class library support.

**Comment by niemyjski** [comment]
Can you remove this repo as it's now located under serilog. I don't know why they didn't just transfer ownership..

**Comment by enkafan** [comment]
you bet. i'll close it now
